# Generated by Django 4.2.7 on 2023-11-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
