# Generated by Django 4.2.7 on 2023-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgs', models.JSONField(default=list)),
            ],
        ),
    ]
