# Generated by Django 4.2.7 on 2023-11-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0003_projectdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='projectIndex',
            field=models.IntegerField(default=0),
        ),
    ]
