# Generated by Django 4.2.7 on 2023-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0004_projectdetail_projectindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='imgs',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='imgs',
            field=models.ManyToManyField(blank=True, related_name='project_images', to='GNU_LikeLion.image'),
        ),
    ]
