# Generated by Django 4.2.7 on 2023-11-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0005_image_remove_projectdetail_imgs_projectdetail_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('images', models.FileField(blank=True, null=True, upload_to='hackathon_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='imgs',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
    ]
