# Generated by Django 4.2.7 on 2023-11-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GNU_LikeLion', '0006_hackathon_remove_projectdetail_imgs_delete_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgs', models.ManyToManyField(blank=True, to='GNU_LikeLion.image')),
            ],
        ),
        migrations.DeleteModel(
            name='Hackathon',
        ),
        migrations.AddField(
            model_name='image',
            name='project_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='GNU_LikeLion.projectdetail'),
        ),
    ]
